data:
  dir: "../data"
  embeddings: "BAAI_embeddings.npy"
  descriptions: "descriptions.csv"
checkpoint:
  dir: "../checkpoints"
model:
  batch_size: 1000
  umap:
    n_neighbors: 30
    n_components: 10
    min_dist: 0.0
    metric: "cosine"
    random_state: 42
  hdbscan:
    min_cluster_size: 400
    metric: "euclidean"
    cluster_selection_method: "eom"
llm:
  model_path: "../models/openhermes-2.5-mistral-7b.Q4_K_M.gguf"
  n_gpu_layers: -1
  n_ctx: 4096
  stop: ["Q:", "\n"]
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
